[package]
name = "nu_from_agp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "nu_plugin_from_agp"
path = "src/main.rs"

[dependencies]
agprefs = "0.3.1"
nu-plugin = "0.85.0"
nu-protocol = "0.85.0"
