[package]
name = "agprefs"
version = "0.1.5"
edition = "2021"
license = "MIT"
description = "A simple parser for the reading agprefs files from lightroom"
readme = "README.md"
repository = "https://github.com/aftershootco/agprefs"
homepage = "https://github.com/aftershootco/agprefs"

[features]

[dependencies]
nom = "7"
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1"
