[package]
name = "agprefstojson"
version = "0.1.0"
edition = "2021"


[lib]
name = "agprefstojson"
crate-type = ["cdylib"]

[dependencies]
agprefs = { version = "0.3.1", path = ".." }
pyo3 = { version = "0.17.3", features = ["extension-module"] }
serde_json = "1.0.87"
